### PR TITLE
[TERMAPI-220] Add the ability to control the screensaver mode

### PR DESCRIPTION
**Pull request by denys-marichev-sumup**
[TERMAPI-220](https://sumupteam.atlassian.net/browse/TERMAPI-220): Add the ability to control the screensaver mode

Screensaver turning on:

Screensaver turning off:

[TERMAPI-220]: https://sumupteam.atlassian.net/browse/TERMAPI-220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by chad-lung-fivestars** [comment]
> [TERMAPI-220](https://sumupteam.atlassian.net/browse/TERMAPI-220): Add the ability to control the screensaver mode
> 

Can you make this a checkbox like the ones below and have it say: `Toggle screensaver`. That will take up less screen space. Unchecked it can be off, checked it can be on.

[TERMAPI-220]: https://sumupteam.atlassian.net/browse/TERMAPI-220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Review by chad-lung-fivestars — CHANGES_REQUESTED** [review]
See comments.

**Comment by denys-marichev-sumup** [comment]
Now when the state of the checkbox changes, a request to enable/disable the screensaver is sent immediately. And now it looks like this:

image

image

@chad-lung-fivestars have I got the idea right?

**Review by chad-lung-fivestars — APPROVED** [review]
Looks good to me. Thanks for making the changes. 👍

**Pull request merged**
